ALTER TABLE users
  ADD COLUMN phone VARCHAR(30) NULL UNIQUE,
  ADD COLUMN termsAccepted BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN registrationComplete BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN freeAccess BOOLEAN NOT NULL DEFAULT FALSE;
